### PR TITLE
add dockerfiles

### PR DESCRIPTION
**Pull request by jordane**

### CODE REVIEW

**Comment by armiller** [comment]
LGTM but you may want the base to Centos 7 now.

**Comment by jldugger** [comment]
@ramereth given that PGD is in 'maintenance mode', do we want to bother deploying this or redoing it on centos7?

**Comment by ramereth** [comment]
@jldugger we need to migrate away from Gentoo at some point with PGD so I think it's still relevant.

**Comment by mathuin** [comment]
@ramereth Any idea where we'll migrate to from Gentoo?

**Comment by ramereth** [comment]
@mathuin CentOS 7

**Comment by mathuin** [comment]
@ramereth Excellent, the project Dockerfile is already set to `FROM centos:7` so we're already well-placed.

**Comment by jldugger** [comment]
based on RT#29216 I don't see any reason to keep this open.

**Pull request closed without merging**
